stm32_simulator:
  ros__parameters:
    wheel_radius_m: 0.03
    wheelbase_m: 0.1312
    track_width_m: 0.1312
    max_wheel_speed_rad_s: 18.0
    max_linear_speed_mps: 0.54
    max_angular_speed_rad_s: 3.0
    command_timeout_sec: 0.25
    control_frequency_hz: 100.0
    telemetry_frequency_hz: 50.0
    encoder_counts_per_revolution: 2048.0
    motor_kp: 0.08
    motor_ki: 0.25
    motor_kd: 0.0005
    command_topic: stm32_cmd_vel
    joint_states_topic: joint_states
    imu_input_topic: imu
    use_joint_encoder_input: true
    use_imu_input: true
    simulation_mode: true
    actuator_topics:
      - /model/amr_omni/joint/omni_wheel_joint_1/cmd_vel
      - /model/amr_omni/joint/omni_wheel_joint_2/cmd_vel
      - /model/amr_omni/joint/omni_wheel_joint_3/cmd_vel
      - /model/amr_omni/joint/omni_wheel_joint_4/cmd_vel
    odom_topic: odom
    imu_output_topic: imu/data_raw
    wheel_state_topic: wheel_state
    diagnostics_topic: diagnostics
    status_topic: status
    odom_frame: odom
    base_frame: base_link
    imu_frame: imu_link
